#!/usr/bin/env bash
# Transfer a file to a server using scp

# Check if correct number of arguments is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Use absolute path to the private key
private_key_path="$(realpath "$4")"

# Transfer the file to the user's home directory on the server using scp
scp -o StrictHostKeyChecking=no -i "$private_key_path" "$1" "$3@$2":~/

# Exit with the scp command's exit status
exit $?

