#!/usr/bin/env bash

# Install nginx web server

# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Ensure Nginx is listening on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx to apply the changes
sudo service nginx restart

# Create a new index.html file with the content "Hello World!"
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Hello World!' > $file1"

# Test the Nginx server using curl
if [ "$(curl -s http://localhost)" == "Hello World!" ]; then
    echo "Nginx installation successful!"
else
    echo "Nginx installation failed."
fi

