#!/usr/bin/env bash
# Configures a new Ubuntu machine to install nginx and set up a page

# Update the package lists for upgrades and new package installations
apt-get update -y

# Install nginx
apt-get install nginx -y

# Start nginx
service nginx start

# Create a new index.html file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Replace the default server block configuration with our new configuration
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx to apply the changes
service nginx restart
