#!/bin/bash

# Define the replacement string with multiple lines
new_string="return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;"

# Specify the file to edit
file="/etc/nginx/sites-available/default"

# Use sed to replace the line
sed -i "/\/redirect_me/ c\\$new_string" $file

# Restart Nginx to apply the changes
service nginx restart

