#!/usr/bin/env bash
# Configures Nginx to have a custom 404 page

# Install Nginx package
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page
echo 'Ceci n'\''est pas une page' | sudo tee /var/www/html/custom_404.html > /dev/null

# Create Nginx configuration for custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
        rewrite ^.*$ /custom_404.html last;
    }
}
EOF'

# Enable the new Nginx configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx to apply changes
sudo service nginx restart

