#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Update and install Nginx
sudo apt -y update
sudo apt -y install nginx

# Set ownership for the web directory
sudo chown -R www-data:www-data /var/www/html

# Create a custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html

# Update the Nginx default site configuration
sudo sed -i '/listen 80 default_server;/a \\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

