#!/usr/bin/env bash

# Install nginx
apt-get -y update
apt-get -y install nginx

# Configure nginx to listen on port 80
sed -i "s/^listen .*/listen 80/" /etc/nginx/sites-enabled/default

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Create a simple HTML page
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html

# Add a redirect and custom error page to the nginx configuration
file="/etc/nginx/sites-enabled/default"
redirect="\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;"
sed -i "/server_name _;/a ${redirect}" "$file"

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
err="\    error_page 404 /custom_404.html;\n\    location = /custom_404.html  {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "/server_name _;/a ${err}" "$file"

# Add a custom header with the hostname
hostname_value=$(hostname)
custom_header="\    add_header X-Served-By $hostname_value;"
sed -i "/server_name _;/a ${custom_header}" "$file"

# Restart Nginx
service nginx restart

# Test the custom header by querying each server's IP
web_server_1="34.198.248.145"
web_server_2="54.89.38.100"

echo "Testing X-Served-By header on $web_server_1:"
curl -sI $web_server_1 | grep X-Served-By

echo "Testing X-Served-By header on $web_server_2:"
curl -sI $web_server_2 | grep X-Served-By

