#!/usr/bin/env bash

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom Nginx configuration file
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/custom_header

# Include the custom configuration in the main Nginx configuration
echo 'include /etc/nginx/custom_header;' | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
sudo service nginx restart

