#!/usr/bin/env bash
# Install the load balancer


sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/nginx
sudo cp /etc/nginx/nginx.cfg /etc/nginx/nginx.cfg.original
sudo sed -i "$ a\listen 70623-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 70623-web-02 54.157.130.186 check\n\tserver 70623-web-01 52.206.18.131 check" /etc/nginx/haproxy.cfg
sudo service nginx start
