#!/usr/bin/env bash
# This script provides answers to questions about types of networks.

# Question 1: What type of network a computer in a local area is connected to?
# Answer: LAN

# Question 2: What type of network could connect an office in one building to another office in a building a few streets away?
# Answer: WAN

# Question 3: What network do you use when you browse www.google.com from your smartphone (not connected to Wi-Fi)?
# Answer: Internet

