#!/usr/bin/env bash
# This script provides answers to questions about MAC and IP addresses.

# Question 1: What is a MAC address?
# Answer: The unique identifier of a network interface

# Question 2: What is an IP address?
# Answer: Is a number that network devices use to connect to networks

