#!/usr/bin/env bash
# This script fixes Nginx not listening on port 80 issue

# Update Nginx configuration to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

