#!/usr/bin/env bash
# This script fixes Nginx not listening on port 80 issue

file=/etc/nginx/sites-available/default
sed -i 's/listen 80 default_server;/listen 80;/g' $file
sudo service nginx restart

