#!/usr/bin/env bash
# This script displays a list of currently running processes, including process hierarchy.

# Use the ps command to display process information in user-oriented format
# You can customize the ps command options to format the output as needed
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
