#!/bin/bash
# This script stops 4-to_infinity_and_beyond process
# It uses kill command to send a signal to the process

# Get the process ID (PID) of 4-to_infinity_and_beyond
pid=$(pgrep 4-to_infinity_and_beyond)

# If the process is running, kill it
if [ -n "$pid" ]; then
    kill "$pid"
fi
