#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the process ID (PID) of 4-to_infinity_and_beyond and send a SIGTERM signal to terminate it.
pkill -f "4-to_infinity_and_beyond"

