#!/usr/bin/env bash
# This script stops the 4-to-infinity-and-beyond process.

# Find the process ID (PID) of 4-to_infinity_and_beyond and send a custom signal to terminate it.
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
  echo "Stopping the 4-to-infinity-and-beyond process..."
  # Send a custom signal (SIGUSR1) to gracefully terminate the process.
  kill -USR1 $pid
else
  echo "Process not found."
fi

