#!/bin/bash
# This script stops 4-to_infinity_and_beyond process

# Get the process ID (PID) of 4-to_infinity_and_beyond
pid=$(ps aux | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

# If the process is running, send a terminate signal
if [ -n "$pid" ]; then
    kill -9 "$pid"
fi
