#!/usr/bin/env bash
# This script tells the story of each user in the /etc/passwd file.

while IFS=: read -r username _ uid gid gecos home shell; do
    passcode=$(echo "$gecos" | cut -d ',' -f 6)
    user_info=$(echo "$gecos" | cut -d ',' -f 5)
    
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < /etc/passwd

