#!/usr/bin/env bash
#Content of 0-block_all_incoming_traffic_but


# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Check ufw status (optional)
sudo ufw status

# Enable ufw
sudo ufw enable

# Set up ufw rules
sudo ufw default deny incoming   # Block all incoming traffic by default
sudo ufw default allow outgoing  # Allow all outgoing traffic by default
sudo ufw allow 22/tcp            # Allow SSH (port 22)
sudo ufw allow 443/tcp           # Allow HTTPS (port 443)
sudo ufw allow 80/tcp            # Allow HTTP (port 80)

# Check ufw status again (optional)
sudo ufw status

