#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server

# Copy the original hosts file to a new file
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
