#!/usr/bin/env bash
# Start the Docker container
sudo docker run -p 8080:80 -d holbertonschool/265-0

# Wait for the container to start (optional)
sleep 2

# Start Apache inside Docker
sudo docker exec -it "$(sudo docker ps -q)" service apache2 start

