#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Change the user that runs the Nginx process in the Nginx configuration file
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf

# Change the port that Nginx listens on in the default site configuration
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server/listen [::]:8080 default_server/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

