#!/usr/bin/env bash
# web debugging
sudo sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen [::]:80 default_server/listen [::]:8080 default_server/g' /etc/nginx/sites-available/default
sudo service nginx restart

