#!/usr/bin/env bash
# This script configures the container to run Nginx as the nginx user and listen on port 8080

sudo service nginx stop
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sudo service nginx start

