#!/usr/bin/env bash

# Get the PID of the master Gunicorn process
master_pid=$(ps auxf | grep gunicorn | grep -v grep | awk '{print $2}')

# Send a HUP signal to the master Gunicorn process
kill -HUP $master_pid

# Wait for the old worker processes to exit
while [ $(ps auxf | grep gunicorn | grep -v grep | wc -l) -gt 1 ]; do
    sleep 1
done

# Wait for the new worker processes to start
while [ $(ps auxf | grep gunicorn | grep -v grep | wc -l) -lt 4 ]; do
    sleep 1
done

echo "Gunicorn reloaded successfully"
