#!/usr/bin/env bash
# Reload Gunicorn without downtime

# Define the name of the Gunicorn application (as per your setup)
APP_NAME="web_flask.0-hello_route:app"

# Define the Gunicorn PID file location
PID_FILE="/var/run/gunicorn.pid"

# Check if the Gunicorn PID file exists
if [ -f "$PID_FILE" ]; then
    # Reload Gunicorn by sending the HUP signal to the master process
    kill -HUP $(cat "$PID_FILE")
    echo "Gunicorn reloaded successfully."
else
    echo "Gunicorn PID file does not exist."
fi

