#!/usr/bin/env bash
# /etc/nginx/sites-available/5-app_server-nginx_config

server {
    listen 80 default_server;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:5003;
    }

    # Serve static assets
    location /static/ {
        alias /path/to/your/AirBnB_clone_v4/web_dynamic/static/;
    }

    # Custom 404 error page
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}
