#!/bin/bash

# Create an RSA key pair
ssh-keygen -t rsa -b 4096 -C "vagrant@ubuntu" -f school -N "betty"

# Display the generated key fingerprint and randomart image
echo "The key fingerprint is:"
cat school.pub | awk '{print $2}'
echo "The key's randomart image is:"
cat school.pub | ssh-keygen -lf /dev/stdin

# Move the private key to the current directory
mv school ~/.ssh/school

# Display the list of files in the current directory
ls

